(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory(require('./engine'));else root.AcceleratorStudioImport=factory(root.AcceleratorAnalytics);})(typeof globalThis==='undefined'?this:globalThis,function(A){
'use strict';const windows={24:'_24h',48:'_48h',168:'_7d',672:'_28d'},metrics=['views','engagedViews','impressions','ctr','retention30','apv','avdSeconds'];const hash=x=>{let h=2166136261;for(const c of JSON.stringify(x)){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return(h>>>0).toString(36)};
function prompt(c){return `In Ask Studio, extract actual analytics for this channel to set up and update Accelerator baselines. Do not estimate, invent, extrapolate or calculate baseline averages. If a report or exact age window is unavailable, use null for missing values and list the limitation. Do not replace engaged views with views. Include the most recent 20 comparable published long-form videos in the current strategy era; keep other formats in separate groups. For each video request exact first 24h, 48h, 7d (168h), and 28d (672h), only where fully completed and available. Use actual publication and capture timestamps with timezone, actual video URL/ID, same traffic filter and measurement definitions. Percentages are percentage numbers (6.2 means 6.2%), AVD is seconds. No credentials or private viewer information.\nReturn a single JSON object in the schema below. Repeat rows for each eligible video and age window. Do not put example data into the output. Keep creatorId exactly ${JSON.stringify(c.id)}; channelName must be the actual channel you are inspecting. requestedCreatorName is ${JSON.stringify(c.name)}. Use coverage exact ONLY when the source actually reports that precise first-hours lifespan, otherwise unknown or partial. definitionId must describe the actual measurement method/version consistently; use unknown if not verified. paid is organic, paid, mixed or unknown. format identifies comparable format, eraId identifies a consistent strategy era; do not infer a changed era from an outlier. job is null unless known. Provide readable source report and filters for every row. Do not guess a missing field.\n${JSON.stringify({schemaVersion:1,creatorId:c.id,channelName:'ACTUAL CHANNEL',observations:[{videoId:'ACTUAL YOUTUBE URL OR ID',title:'ACTUAL TITLE',publishedAt:'ISO TIMESTAMP',capturedAt:'ISO TIMESTAMP',windowHours:168,format:'edited-long-form',eraId:'current',job:null,definitionId:'unknown',coverage:'unknown',paid:'unknown',traffic:'all',source:'ACTUAL REPORT AND FILTERS',metrics:Object.fromEntries(metrics.map(k=>[k,null]))}],channelPeriods:[],limitations:[]},null,2)}\nOptional channelPeriods: two non-overlapping completed 90-day periods, each {start:"YYYY-MM-DD",end:"YYYY-MM-DD",source:"report and filters",metrics:{views:null,engagedViews:null,impressions:null,ctr:null,watchTime:null,newViewers:null,returning:null,qualifiedLeads:null}}. watchTime is hours, ctr is percentage. Attribution outside Studio must be null. Do not label a 28-day rolling audience number as a 90-day unique viewer count. If you cannot produce exact data, explain the unavailable reports in limitations and omit those observations rather than fabricate them. Return raw measurements, not coaching recommendations.`;}
function parse(text,c,prior,now=new Date().toISOString()){
 if(typeof text!=='string'||text.length>1500000)throw Error('Paste a response under 1.5 MB.');
 let raw=text.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');let data;try{data=JSON.parse(raw);}catch{throw Error('Paste the complete JSON object from Studio. Ask it to return the requested JSON format if it returned prose.');}
 if(data.schemaVersion!==1||data.creatorId!==c.id)throw Error('This response belongs to a different creator or prompt version. Copy a fresh prompt for the selected creator.');
 if(!data.channelName||!Array.isArray(data.observations)||data.observations.length>500)throw Error('Channel name and an observations array (at most 500 rows) are required.');
 let next=prior||A.emptyStore(),added=0,duplicates=0;const groups=new Map(),seen=new Set();
 for(const row of data.observations){
  if(!row||!windows[row.windowHours]||!row.metrics)throw Error('Each row needs a supported exact age window and metrics.');
  const clean={};for(const k of metrics){const v=row.metrics[k];if(v!==null&&v!==undefined&&(typeof v!=='number'||!Number.isFinite(v)))throw Error(k+' must be a number or null.');clean[k]=v==null?null:['ctr','retention30','apv'].includes(k)?v/100:v;}
  const source=typeof row.source==='string'?row.source:'';if(!source.trim())throw Error('Each observation needs its actual source report.');
  const o={id:'studio:'+hash([row.videoId,row.windowHours,clean,row.capturedAt,row.definitionId,row.publishedAt,row.coverage,row.format,row.eraId,row.job,row.paid,row.traffic,source]),creatorId:c.id,videoId:row.videoId,title:String(row.title||row.videoId),publishedAt:row.publishedAt,capturedAt:row.capturedAt,windowHours:row.windowHours,format:row.format,eraId:row.eraId,job:row.job||null,definitionId:row.definitionId||'unknown',coverage:row.coverage||'unknown',paid:row.paid||'unknown',traffic:row.traffic||'all',source,metrics:clean};
  const key=A.canonicalVideoId(o.videoId)+':'+o.windowHours;if(seen.has(key))throw Error('The response contains duplicate video/window rows. Keep one report per checkpoint.');seen.add(key);
  if(next.observations.some(x=>x.id===o.id)){duplicates++;continue;}next=A.acceptObservation(next,o,now);added++;
  const g=[c.id,o.windowHours,o.format,o.eraId,o.definitionId,o.paid,o.traffic];groups.set(hash(g),o);
 }
 for(const [id,o] of groups){const policyId='studio-policy:'+id;if(next.policies.some(p=>p.id===policyId))continue;const p={id:policyId,creatorId:c.id,label:o.windowHours+'h · '+o.format,windowHours:o.windowHours,format:o.format,eraId:o.eraId,definitionId:o.definitionId,paid:o.paid,traffic:o.traffic,primaryMetric:'views',cohortLimit:20,refreshAfter:4};const candidate=A.createPolicy(next,p,now);if(candidate.baselines.at(-1).metrics.views.n>=5)next=candidate;}
 const periods=[];for(const p of data.channelPeriods||[]){if(!/^\d{4}-\d{2}-\d{2}$/.test(p.start)||!/^\d{4}-\d{2}-\d{2}$/.test(p.end)||(Date.parse(p.end)-Date.parse(p.start))/86400000!==89||p.end>=now.slice(0,10)||!p.source)throw Error('Channel periods must be completed 90-day ranges with a source.');const m={};for(const k of ['views','engagedViews','impressions','ctr','watchTime','newViewers','returning','qualifiedLeads']){const v=p.metrics?.[k];if(v!=null&&(typeof v!=='number'||!Number.isFinite(v)||v<0||(k==='ctr'&&v>100)))throw Error('Invalid channel metric '+k);m[k]=v??null;}periods.push({start:p.start,end:p.end,source:String(p.source),metrics:m});}
 periods.sort((a,b)=>a.start.localeCompare(b.start));for(let i=1;i<periods.length;i++)if(periods[i-1].end>=periods[i].start)throw Error('Channel periods must not overlap.');
 return {next,added,duplicates,channelName:String(data.channelName),periods,limitations:(data.limitations||[]).map(String),signature:JSON.stringify(prior||A.emptyStore())};
}
return {prompt,parse,hash,metrics,windows};
});
