(()=>{
const ENDPOINT='https://pqggobwpazihraeqvspc.supabase.co/functions/v1/creator-portal',root=document.getElementById('creator-portal');
let token='',link=null,doc=null,saving=false,timer=null,toast=null,changeSeq=0,savedSeq=0,saveQueued=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),pick=(a,b)=>String(a||b||'');
function readToken(){const h=decodeURIComponent((location.hash||'').replace(/^#/,'')).trim(),q=new URLSearchParams(location.search).get('token')||'';if(h)return h;if(q){history.replaceState(null,'',location.pathname+'#'+encodeURIComponent(q));return q}return''}
async function post(body){const r=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store'});let d={};try{d=await r.json()}catch{}if(!r.ok){const e=new Error(d.error||('Request failed '+r.status));e.status=r.status;e.data=d;throw e}return d}
function notify(t){toast?.remove();const n=document.createElement('div');n.className='notice';n.textContent=t;document.body.appendChild(n);toast=n;setTimeout(()=>{if(toast===n){n.remove();toast=null}},2200)}
const videos=()=>Array.isArray(doc?.payload?.videos)?doc.payload.videos:[],byId=id=>videos().find(v=>String(v.id)===String(id));
function opts(cur){return['Working on it','Needs coach input','Ready for review','Filming','Editing','Ready to publish','Published'].map(x=>'<option '+(x===cur?'selected':'')+'>'+esc(x)+'</option>').join('')}
function card(v){const c=v.creator||{},k=v.coach||{},ready=!!c.readyForReview,status=pick(c.status,k.stage)||'Working on it',tasks=Array.isArray(k.tasks)?k.tasks:[],done=new Set(c.completedTaskIds||[]);
return '<section class="card"><div class="video-head"><div><h2>'+esc(pick(c.titleDraft,k.title)||'Untitled video')+'</h2><small>'+esc(k.publishDate?('Target publish: '+k.publishDate):(k.stage||'Shared video'))+'</small></div><span class="pill '+(ready?'ready':'')+'">'+(ready?'Ready for review':'In progress')+'</span></div>'+
(k.direction?'<div class="coach"><b>Coach direction</b>'+esc(k.direction).replace(/\n/g,'<br>')+'</div>':'')+
(tasks.length?'<div class="coach"><b>Next steps</b><div class="tasks">'+tasks.map(t=>'<label class="task"><input type="checkbox" data-task="'+esc(t.id)+'" data-video="'+esc(v.id)+'" '+(done.has(t.id)?'checked':'')+'><span>'+esc(t.text)+'</span></label>').join('')+'</div></div>':'')+
'<div class="grid"><label>Working title<input data-field="titleDraft" data-video="'+esc(v.id)+'" value="'+esc(pick(c.titleDraft,k.title))+'"></label><label>Status<select data-field="status" data-video="'+esc(v.id)+'">'+opts(status)+'</select></label>'+
'<label>Thumbnail text<input data-field="thumbnailTextDraft" data-video="'+esc(v.id)+'" value="'+esc(pick(c.thumbnailTextDraft,k.thumbnailText))+'"></label><label class="full">Thumbnail concept<textarea data-field="thumbnailConceptDraft" data-video="'+esc(v.id)+'">'+esc(pick(c.thumbnailConceptDraft,k.thumbnailConcept))+'</textarea></label>'+
'<label class="full">Hook<textarea data-field="hookDraft" data-video="'+esc(v.id)+'">'+esc(pick(c.hookDraft,k.hookDraft))+'</textarea></label><label>Who is this for?<textarea data-field="viewerDraft" data-video="'+esc(v.id)+'">'+esc(pick(c.viewerDraft,k.viewer))+'</textarea></label><label>What should they get?<textarea data-field="promiseResultDraft" data-video="'+esc(v.id)+'">'+esc(pick(c.promiseResultDraft,k.promiseResult))+'</textarea></label>'+
'<label class="full">Outline / working notes<textarea class="tall" data-field="outlineNotesDraft" data-video="'+esc(v.id)+'">'+esc(pick(c.outlineNotesDraft,k.outlineNotes))+'</textarea></label><label class="full">Notes for your coach<textarea data-field="notes" data-video="'+esc(v.id)+'">'+esc(c.notes||'')+'</textarea></label></div>'+
'<div class="actions"><button class="btn primary" type="button" data-save>Save changes</button><button class="btn '+(ready?'':'good')+'" type="button" data-ready="'+esc(v.id)+'">'+(ready?'Mark as still working':'Ready for coach review')+'</button></div></section>'}
function render(){if(!doc)return;const p=doc.payload||{},c=p.creator||{},vs=videos();root.innerHTML='<div class="top"><div><div class="brand">'+(link?.scope==='video'?'Shared Video':'Creator Workspace')+'</div><h1>'+esc(c.name||'Your workspace')+'</h1><div class="muted">'+esc(c.channelName||'Work on the videos you and your coach are building together.')+'</div></div><div class="save-state" id="portal-save-state">'+(changeSeq>savedSeq?'Unsaved changes':'Saved')+'</div></div>'+(c.instructions?'<section class="card instructions"><b>What to focus on</b><div>'+esc(c.instructions).replace(/\n/g,'<br>')+'</div></section>':'')+(vs.length?vs.map(card).join(''):'<section class="card empty"><h2>No video shared yet</h2><p class="muted">Ask your coach to update this private link.</p></section>');
root.querySelectorAll('[data-field]').forEach(el=>el.addEventListener(el.tagName==='SELECT'?'change':'input',edit));root.querySelectorAll('[data-task]').forEach(el=>el.addEventListener('change',task));root.querySelectorAll('[data-ready]').forEach(el=>el.addEventListener('click',ready));root.querySelectorAll('[data-save]').forEach(el=>el.addEventListener('click',()=>save(true)))}
function scheduleSave(){clearTimeout(timer);timer=setTimeout(()=>save(false),900)}
function dirty(){changeSeq++;const e=document.getElementById('portal-save-state');if(e)e.textContent='Unsaved changes';scheduleSave()}
function edit(e){const v=byId(e.currentTarget.dataset.video);if(!v)return;v.creator=v.creator||{};v.creator[e.currentTarget.dataset.field]=e.currentTarget.value;dirty()}
function task(e){const v=byId(e.currentTarget.dataset.video);if(!v)return;v.creator=v.creator||{};const s=new Set(v.creator.completedTaskIds||[]);e.currentTarget.checked?s.add(e.currentTarget.dataset.task):s.delete(e.currentTarget.dataset.task);v.creator.completedTaskIds=[...s];dirty()}
async function ready(e){const v=byId(e.currentTarget.dataset.ready);if(!v)return;v.creator=v.creator||{};v.creator.readyForReview=!v.creator.readyForReview;if(v.creator.readyForReview)v.creator.status='Ready for review';dirty();const ok=await save(true);render();if(!ok){const state=document.getElementById('portal-save-state');if(state)state.textContent='Could not save'}}
async function save(show){if(!doc)return false;if(saving){saveQueued=true;if(show)notify('Saving your latest changes…');return false}clearTimeout(timer);saving=true;saveQueued=false;const seq=changeSeq,local=JSON.parse(JSON.stringify(doc.payload)),el=document.getElementById('portal-save-state');if(el)el.textContent='Saving…';let ok=false;try{let out;try{out=await post({action:'portal-save',token,version:doc.version,payload:local})}catch(err){if(err.status===409&&err.data?.document){const fresh=err.data.document,map=new Map((local.videos||[]).map(v=>[String(v.id),v.creator||{}]));for(const v of fresh.payload?.videos||[])if(map.has(String(v.id)))v.creator=map.get(String(v.id));doc.version=fresh.version;out=await post({action:'portal-save',token,version:doc.version,payload:fresh.payload})}else throw err}doc.version=out.version;doc.creatorRevision=out.creatorRevision;doc.updatedAt=out.updatedAt;savedSeq=Math.max(savedSeq,seq);ok=true;const state=document.getElementById('portal-save-state');if(state)state.textContent=changeSeq>savedSeq?'Saving latest changes…':'Saved just now';if(show)notify('Saved')}catch(err){const state=document.getElementById('portal-save-state');if(state)state.textContent='Could not save';notify(err.message==='LINK_NOT_FOUND_OR_REVOKED'?'This share link is no longer active.':'Could not save. Your changes are still on this page.')}finally{saving=false;if(saveQueued||changeSeq>savedSeq){saveQueued=false;clearTimeout(timer);timer=setTimeout(()=>save(false),120)}}return ok}
async function boot(){token=readToken();if(!token){root.innerHTML='<div class="card error"><h1>This workspace link is incomplete</h1><p>Ask your coach to send the full private video link.</p></div>';return}try{const data=await post({action:'portal-get',token});link=data.link;doc=data.document;render()}catch(err){root.innerHTML='<div class="card error"><h1>Workspace unavailable</h1><p>'+(err.message==='LINK_NOT_FOUND_OR_REVOKED'?'This private link has been revoked, expired, or replaced. Ask your coach for the current link.':'The workspace could not load. Please try the link again.')+'</p></div>'}}
boot();
})();