(()=>{
if(window.__acceleratorCreatorSharing)return;window.__acceleratorCreatorSharing=true;
const ENDPOINT='https://pqggobwpazihraeqvspc.supabase.co/functions/v1/creator-portal',PUB='sb_publishable_VgGebMpW9tBcCiQlRdnzpA__rbATAaT',AUTH='sb-pqggobwpazihraeqvspc-auth-token';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function bind(n){try{return(0,eval)('typeof '+n+'!=="undefined"?'+n+':undefined')}catch{return undefined}}
function state(){const s=bind('state');return s&&typeof s==='object'?s:null}
function creator(){const s=state();return s?.creators?.find(c=>String(c.id)===String(s.currentCreatorId))||null}
function wid(){try{return window.__acceleratorSaveDiagnostics?.().workspaceId||null}catch{return null}}
function tokenIn(x,d=0){if(!x||d>5)return null;if(typeof x==='object'){if(typeof x.access_token==='string')return x.access_token;for(const v of Object.values(x)){const t=tokenIn(v,d+1);if(t)return t}}return null}
function auth(){try{return tokenIn(JSON.parse(localStorage.getItem(AUTH)||'null'))}catch{return null}}
async function api(body){const t=auth();if(!t)throw new Error('Cloud sign-in is required before creating a creator link.');const r=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json','apikey':PUB,'Authorization':'Bearer '+t},body:JSON.stringify(body),cache:'no-store'});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||('Request failed '+r.status));return d}
const obj=v=>v&&typeof v==='object'&&!Array.isArray(v)?v:{},str=v=>typeof v==='string'?v:'';
function source(v){const p=obj(v.package),pr=obj(v.promise),h=obj(v.hook),s=obj(v.structure);return{title:str(p.finalTitle)||str(p.workingTitle)||str(v.title),thumbnailText:str(p.thumbnailText),thumbnailConcept:str(p.thumbnailConcept),hookDraft:str(h.draft)||str(s.hook),viewer:str(pr.viewer)||str(v.viewer)||str(v.exactViewer),promiseResult:str(pr.result)||str(v.desiredOutcome),outlineNotes:str(s.notes),stage:str(v.stage),publishDate:str(v.publishDate)}}
function taskId(t){let h=2166136261;for(let i=0;i<t.length;i++){h^=t.charCodeAt(i);h=Math.imul(h,16777619)}return'task-'+(h>>>0).toString(36)}
const linkUrl=t=>location.origin+'/creator.html#'+encodeURIComponent(t);
let dialog,info=null,checking=false;
function css(){if(document.getElementById('creator-share-style'))return;const s=document.createElement('style');s.id='creator-share-style';s.textContent='#creator-share-launch{position:fixed;right:20px;bottom:20px;z-index:9000;border:0;border-radius:999px;background:#234f52;color:#fff;padding:11px 15px;font:800 13px/1 Inter,system-ui;box-shadow:0 8px 28px rgba(0,0,0,.18);cursor:pointer}#creator-share-launch[data-review="true"]{background:#2f8464}.cshare{padding:20px}.cshare h2{margin:0 0 4px}.cshare .muted{opacity:.66}.cshare-head{display:flex;justify-content:space-between;gap:14px}.cshare-actions{display:flex;gap:8px;flex-wrap:wrap;margin:14px 0}.cshare button{border:1px solid var(--line,#d8e0e3);background:var(--panel,#fff);color:inherit;border-radius:9px;padding:9px 12px;font-weight:800;cursor:pointer}.cshare button.primary{background:#234f52;color:#fff;border-color:#234f52}.cshare button.danger{color:#9a3d3d}.cshare textarea{width:100%;min-height:82px;border:1px solid var(--line,#d8e0e3);border-radius:9px;padding:9px;background:transparent;color:inherit;font:inherit;resize:vertical}.cshare label{display:grid;gap:5px;font-size:12px;font-weight:800}.cshare-video{border:1px solid var(--line,#d8e0e3);border-radius:12px;padding:13px;margin:10px 0}.cshare-video-head{display:flex;gap:8px;align-items:flex-start}.cshare-video-head input{margin-top:4px}.cshare-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:10px}.cshare-msg{min-height:20px;font-size:12px}.cshare-review{padding:11px;border-radius:10px;background:rgba(47,132,100,.09);margin:10px 0}.cshare-note{padding:9px;border-left:3px solid #55757a;background:rgba(85,117,122,.06);margin-top:8px;font-size:13px}@media(max-width:700px){#creator-share-launch{right:12px;bottom:12px}.cshare-grid{grid-template-columns:1fr}.cshare-head{display:block}}';document.head.appendChild(s)}
function ensureDialog(){if(dialog)return dialog;dialog=document.createElement('dialog');dialog.id='creator-share-dialog';dialog.style.cssText='width:min(920px,94vw);max-height:92vh;border:1px solid #cbd6da;border-radius:15px;padding:0;background:var(--panel,#fff);color:var(--text,#17212b)';dialog.innerHTML='<div id="creator-share-body"></div>';document.body.appendChild(dialog);dialog.addEventListener('click',async e=>{const a=e.target.closest('[data-cshare]')?.dataset.cshare;if(!a)return;try{if(a==='close')dialog.close();else if(a==='publish')await publish();else if(a==='copy')await copy();else if(a==='open')openLink();else if(a==='refresh')await reload(true);else if(a==='apply')await apply();else if(a==='rotate')await rotate();else if(a==='revoke')await revoke()}catch(err){msg(err.message||'Something went wrong.',true)}});return dialog}
function existing(id){return info?.document?.payload?.videos?.find(v=>String(v.id)===String(id))||null}
function render(c){const link=info?.link,doc=info?.document,ids=new Set((doc?.payload?.videos||[]).map(v=>String(v.id))),vs=Array.isArray(c.videos)?c.videos:[],url=link?.token?linkUrl(link.token):'',review=doc?.needsReview;
const rows=vs.map(v=>{const ex=existing(v.id),checked=link?ids.has(String(v.id)):true,d=ex?.coach?.direction||'',tasks=(ex?.coach?.tasks||[]).map(t=>t.text).join('\n'),cr=ex?.creator||{},note=(cr.notes||cr.readyForReview)?'<div class="cshare-note">'+(cr.readyForReview?'<b>Ready for review.</b> ':'')+esc(cr.notes||'')+'</div>':'';return'<div class="cshare-video"><div class="cshare-video-head"><input type="checkbox" data-share-video value="'+esc(v.id)+'" '+(checked?'checked':'')+'><div><b>'+esc(source(v).title||'Untitled video')+'</b><div class="muted">'+esc(v.stage||'Video')+'</div></div></div>'+note+'<div class="cshare-grid"><label>Coach direction<textarea data-direction="'+esc(v.id)+'">'+esc(d)+'</textarea></label><label>Next steps, one per line<textarea data-tasks="'+esc(v.id)+'">'+esc(tasks)+'</textarea></label></div></div>'}).join('');
document.getElementById('creator-share-body').innerHTML='<div class="cshare"><div class="cshare-head"><div><h2>'+esc(c.name)+' · Creator Workspace</h2><div class="muted">No creator account required. Only the fields you publish here are shared.</div></div><button data-cshare="close">Close</button></div>'+(review?'<div class="cshare-review"><b>Creator changes are waiting for review.</b> Apply the editable video fields back into your dashboard when you are ready.</div>':'')+'<label>Shared instructions<textarea id="cshare-instructions">'+esc(doc?.payload?.creator?.instructions||'')+'</textarea></label><div class="cshare-actions"><button class="primary" data-cshare="publish">'+(link?'Update shared workspace':'Create private share link')+'</button>'+(link?'<button data-cshare="copy">Copy link</button><button data-cshare="open">Open creator view</button><button data-cshare="refresh">Check for changes</button>':'')+(review?'<button class="primary" data-cshare="apply">Apply creator changes</button>':'')+'</div>'+(url?'<div class="muted">Private link: '+esc(url)+'</div>':'')+'<h3>Shared videos</h3>'+(rows||'<p class="muted">Create a video for this creator first, then come back here to share it.</p>')+(link?'<div class="cshare-actions"><button data-cshare="rotate">Rotate private link</button><button class="danger" data-cshare="revoke">Revoke link</button></div>':'')+'<div id="cshare-msg" class="cshare-msg"></div></div>'}
function msg(t,bad=false){const e=document.getElementById('cshare-msg');if(e){e.textContent=t;e.style.color=bad?'#a33':'inherit'}}
function snapshot(c){const ids=new Set([...dialog.querySelectorAll('[data-share-video]:checked')].map(x=>x.value));return{schemaVersion:1,creator:{id:String(c.id),name:c.name||'',channelName:c.channelName||'',instructions:document.getElementById('cshare-instructions')?.value||''},videos:(c.videos||[]).filter(v=>ids.has(String(v.id))).map(v=>{const s=source(v),lines=(dialog.querySelector('[data-tasks="'+CSS.escape(String(v.id))+'"]')?.value||'').split(/\n+/).map(x=>x.trim()).filter(Boolean).slice(0,20);return{id:String(v.id),coach:{...s,direction:dialog.querySelector('[data-direction="'+CSS.escape(String(v.id))+'"]')?.value||'',tasks:lines.map(t=>({id:taskId(t),text:t}))},creator:{}}})}}
async function reload(show=false){const c=creator(),w=wid();if(!c)return;if(!w)throw new Error('Cloud workspace is still loading. Try again in a moment.');info=await api({action:'owner-get',workspaceId:w,creatorId:String(c.id)});render(c);launcher(!!info?.document?.needsReview);if(show)msg('Checked for creator changes.')}
async function open(){const c=creator();if(!c)return;ensureDialog();document.getElementById('creator-share-body').innerHTML='<div class="cshare"><b>Loading creator workspace…</b></div>';if(!dialog.open)dialog.showModal();try{await reload(false)}catch(err){document.getElementById('creator-share-body').innerHTML='<div class="cshare"><h2>Creator Workspace</h2><p>'+esc(err.message)+'</p><button data-cshare="close">Close</button></div>'}}
async function publish(){const c=creator(),w=wid(),payload=snapshot(c);if(!payload.videos.length)return msg('Choose at least one video to share.',true);msg('Publishing…');info=await api({action:'publish',workspaceId:w,creatorId:String(c.id),payload});render(c);msg('Shared workspace updated.');launcher(!!info?.document?.needsReview)}
async function copy(){if(!info?.link?.token)return;const u=linkUrl(info.link.token);try{await navigator.clipboard.writeText(u);msg('Private link copied.')}catch{prompt('Copy this private creator link:',u)}}
function openLink(){if(info?.link?.token)window.open(linkUrl(info.link.token),'_blank','noopener,noreferrer')}
async function rotate(){if(!confirm('Replace the current private link? The old link will stop working immediately.'))return;const c=creator(),w=wid(),payload=snapshot(c);await api({action:'rotate',workspaceId:w,creatorId:String(c.id),payload});await reload(false);msg('Private link rotated. Copy the new link.')}
async function revoke(){if(!info?.link?.id||!confirm('Revoke this creator link? The creator will no longer be able to open it.'))return;const c=creator(),w=wid();await api({action:'revoke',workspaceId:w,creatorId:String(c.id),linkId:info.link.id});info={link:null,document:null};render(c);msg('Link revoked.');launcher(false)}
function ensure(o,k){if(!o[k]||typeof o[k]!=='object'||Array.isArray(o[k]))o[k]={};return o[k]}
async function apply(){const c=creator(),w=wid();await reload(false);const p=info?.document?.payload;if(!p)return;let n=0;for(const s of p.videos||[]){const v=(c.videos||[]).find(x=>String(x.id)===String(s.id));if(!v)continue;const cr=s.creator||{},pkg=ensure(v,'package'),hook=ensure(v,'hook'),pr=ensure(v,'promise'),st=ensure(v,'structure'),put=(o,k,val)=>{if(typeof val==='string'&&val.trim()&&o[k]!==val){o[k]=val;n++}};put(pkg,'workingTitle',cr.titleDraft);put(pkg,'thumbnailText',cr.thumbnailTextDraft);put(pkg,'thumbnailConcept',cr.thumbnailConceptDraft);put(hook,'draft',cr.hookDraft);put(pr,'viewer',cr.viewerDraft);put(pr,'result',cr.promiseResultDraft);put(st,'notes',cr.outlineNotesDraft)}const save=bind('save');if(typeof save==='function')save();const rer=bind('render');if(typeof rer==='function')rer();if(info?.link?.id)await api({action:'ack',workspaceId:w,creatorId:String(c.id),linkId:info.link.id});await reload(false);msg(n?('Applied '+n+' creator edit'+(n===1?'':'s')+' to the video workspace.'):'Reviewed. No editable fields needed to change.');launcher(false)}
function launcher(review){let b=document.getElementById('creator-share-launch'),c=creator();if(!c){b?.remove();return}if(!b){css();b=document.createElement('button');b.id='creator-share-launch';b.addEventListener('click',open);document.body.appendChild(b)}b.dataset.review=review?'true':'false';b.textContent=review?'Creator updates ready':'Creator workspace'}
async function check(){if(checking)return;const c=creator();if(!c)return launcher(false);checking=true;try{const w=wid();if(!w)return launcher(false);const d=await api({action:'owner-get',workspaceId:w,creatorId:String(c.id)});if(String(c.id)===String(creator()?.id))launcher(!!d?.document?.needsReview)}catch{launcher(false)}finally{checking=false}}
let last='';function paint(){const id=String(creator()?.id||'');launcher(false);if(id&&id!==last){last=id;setTimeout(check,500)}if(!id)last=''}
new MutationObserver(()=>requestAnimationFrame(paint)).observe(document.documentElement,{childList:true,subtree:true});setInterval(check,60000);setTimeout(paint,1200);window.AcceleratorCreatorSharing={open,check};
})();