(()=>{
if(window.__acceleratorCreatorSharing)return;window.__acceleratorCreatorSharing=true;
const ENDPOINT='https://pqggobwpazihraeqvspc.supabase.co/functions/v1/creator-portal',PUB='sb_publishable_VgGebMpW9tBcCiQlRdnzpA__rbATAaT',AUTH='sb-pqggobwpazihraeqvspc-auth-token';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function bind(n){try{return(0,eval)('typeof '+n+'!=="undefined"?'+n+':undefined')}catch{return undefined}}
function appState(){const s=bind('state');return s&&typeof s==='object'?s:null}
function getCreator(id){return appState()?.creators?.find(c=>String(c.id)===String(id))||null}
function getVideo(c,id){return c?.videos?.find(v=>String(v.id)===String(id))||null}
function currentCreator(){const s=appState();return getCreator(s?.currentCreatorId)}
function currentVideo(){const s=appState(),c=currentCreator();return getVideo(c,s?.currentVideoId)}
function wid(){try{return window.__acceleratorSaveDiagnostics?.().workspaceId||null}catch{return null}}
function tokenIn(x,d=0){if(!x||d>5)return null;if(typeof x==='object'){if(typeof x.access_token==='string')return x.access_token;for(const v of Object.values(x)){const t=tokenIn(v,d+1);if(t)return t}}return null}
function auth(){try{return tokenIn(JSON.parse(localStorage.getItem(AUTH)||'null'))}catch{return null}}
async function api(body){const t=auth();if(!t)throw new Error('Cloud sign-in is required before creating a share link.');const r=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json','apikey':PUB,'Authorization':'Bearer '+t},body:JSON.stringify(body),cache:'no-store'});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||('Request failed '+r.status));return d}
const obj=v=>v&&typeof v==='object'&&!Array.isArray(v)?v:{},str=v=>typeof v==='string'?v:'';
function source(v){const p=obj(v.package),pr=obj(v.promise),h=obj(v.hook),s=obj(v.structure);return{title:str(p.finalTitle)||str(p.workingTitle)||str(v.title),thumbnailText:str(p.thumbnailText),thumbnailConcept:str(p.thumbnailConcept),hookDraft:str(h.draft)||str(s.hook),viewer:str(pr.viewer)||str(v.viewer?.problem)||str(v.exactViewer),promiseResult:str(pr.result)||str(v.desiredOutcome),outlineNotes:str(s.notes),stage:str(v.stage),publishDate:str(v.publishDate)}}
function taskId(t){let h=2166136261;for(let i=0;i<t.length;i++){h^=t.charCodeAt(i);h=Math.imul(h,16777619)}return'task-'+(h>>>0).toString(36)}
const linkUrl=t=>location.origin+'/creator.html#'+encodeURIComponent(t);
let dialog=null,info=null,active=null;
function css(){if(document.getElementById('creator-share-style'))return;const s=document.createElement('style');s.id='creator-share-style';s.textContent='.creator-share-row-actions{display:flex;gap:6px;align-items:center;justify-content:flex-end}.creator-share-inline{white-space:nowrap}.creator-share-inline[data-review="true"],.creator-share-planner[data-review="true"]{border-color:#75ae96!important;background:#eef8f3!important;color:#23664d!important}#creator-share-dialog{width:min(760px,94vw);max-height:92vh;border:1px solid #cbd6da;border-radius:15px;padding:0;background:var(--panel,#fff);color:var(--text,#17212b)}.cshare{padding:20px}.cshare h2{margin:0 0 4px}.cshare .muted{opacity:.66}.cshare-head{display:flex;justify-content:space-between;gap:14px}.cshare-actions{display:flex;gap:8px;flex-wrap:wrap;margin:14px 0}.cshare button{border:1px solid var(--line,#d8e0e3);background:var(--panel,#fff);color:inherit;border-radius:9px;padding:9px 12px;font-weight:800;cursor:pointer}.cshare button.primary{background:#234f52;color:#fff;border-color:#234f52}.cshare button.danger{color:#9a3d3d}.cshare textarea{width:100%;min-height:92px;border:1px solid var(--line,#d8e0e3);border-radius:9px;padding:9px;background:transparent;color:inherit;font:inherit;resize:vertical}.cshare label{display:grid;gap:5px;font-size:12px;font-weight:800;margin-top:12px}.cshare-review{padding:11px;border-radius:10px;background:rgba(47,132,100,.09);margin:12px 0}.cshare-note{padding:9px;border-left:3px solid #55757a;background:rgba(85,117,122,.06);margin-top:8px;font-size:13px}.cshare-link{font-size:11px;overflow-wrap:anywhere}.cshare-msg{min-height:20px;font-size:12px;margin-top:8px}@media(max-width:700px){.cshare-head{display:block}.creator-share-row-actions{gap:4px}.creator-share-inline{padding-inline:8px!important}}';document.head.appendChild(s)}
function ensureDialog(){if(dialog)return dialog;css();dialog=document.createElement('dialog');dialog.id='creator-share-dialog';dialog.innerHTML='<div id="creator-share-body"></div>';document.body.appendChild(dialog);dialog.addEventListener('click',async e=>{const a=e.target.closest('[data-cshare]')?.dataset.cshare;if(!a)return;try{if(a==='close')dialog.close();else if(a==='publish')await publish();else if(a==='copy')await copy();else if(a==='open')openLink();else if(a==='refresh')await reload(true);else if(a==='apply')await applyChanges();else if(a==='rotate')await rotate();else if(a==='revoke')await revoke()}catch(err){msg(err.message||'Something went wrong.',true)}});return dialog}
function ctx(){const c=getCreator(active?.creatorId),v=getVideo(c,active?.videoId);return{c,v}}
function existing(){return info?.document?.payload?.videos?.[0]||null}
function render(){const {c,v}=ctx();if(!c||!v)return;const ex=existing(),cr=ex?.creator||{},link=info?.link,review=!!info?.document?.needsReview,title=source(v).title||'Untitled video',tasks=(ex?.coach?.tasks||[]).map(t=>t.text).join('\n');
document.getElementById('creator-share-body').innerHTML='<div class="cshare"><div class="cshare-head"><div><div class="muted">Share this video</div><h2>'+esc(title)+'</h2><div class="muted">'+esc(c.name)+' · no creator account required</div></div><button data-cshare="close">Close</button></div>'+
(review?'<div class="cshare-review"><b>Creator changes are ready for review.</b>'+(cr.notes?'<div class="cshare-note">'+esc(cr.notes)+'</div>':'')+'</div>':'')+
'<label>What should they focus on?<textarea id="cshare-instructions">'+esc(info?.document?.payload?.creator?.instructions||'')+'</textarea></label>'+
'<label>Coach direction for this video<textarea id="cshare-direction">'+esc(ex?.coach?.direction||'')+'</textarea></label>'+
'<label>Next steps, one per line<textarea id="cshare-tasks">'+esc(tasks)+'</textarea></label>'+
'<div class="muted" style="margin-top:12px">They can work on the title, thumbnail, hook, viewer, promise, outline, notes, and task status. Your internal strategy and analytics are not shared.</div>'+
'<div class="cshare-actions"><button class="primary" data-cshare="publish">'+(link?'Update shared video':'Create private video link')+'</button>'+(link?'<button data-cshare="copy">Copy share link</button><button data-cshare="open">Open creator view</button><button data-cshare="refresh">Check for updates</button>':'')+(review?'<button class="primary" data-cshare="apply">Apply creator changes</button>':'')+'</div>'+
(link?'<div class="cshare-link muted">'+esc(linkUrl(link.token))+'</div><div class="cshare-actions"><button data-cshare="rotate">Rotate link</button><button class="danger" data-cshare="revoke">Revoke link</button></div>':'')+'<div id="cshare-msg" class="cshare-msg"></div></div>';
markButtons(active.videoId,review)}
function msg(t,bad=false){const e=document.getElementById('cshare-msg');if(e){e.textContent=t;e.style.color=bad?'#a33':'inherit'}}
function snapshot(){const {c,v}=ctx(),s=source(v),lines=(document.getElementById('cshare-tasks')?.value||'').split(/\n+/).map(x=>x.trim()).filter(Boolean).slice(0,20);return{schemaVersion:1,creator:{id:String(c.id),name:c.name||'',channelName:c.channelName||'',instructions:document.getElementById('cshare-instructions')?.value||''},videos:[{id:String(v.id),coach:{...s,direction:document.getElementById('cshare-direction')?.value||'',tasks:lines.map(t=>({id:taskId(t),text:t}))},creator:{}}]}}
async function reload(show=false){const {c,v}=ctx(),w=wid();if(!c||!v)return;if(!w)throw new Error('Cloud workspace is still loading. Try again in a moment.');info=await api({action:'owner-get',workspaceId:w,creatorId:String(c.id),videoId:String(v.id)});render();if(show)msg('Checked for creator changes.')}
async function openShare(creatorId,videoId){active={creatorId:String(creatorId),videoId:String(videoId)};const {c,v}=ctx();if(!c||!v)return;ensureDialog();document.getElementById('creator-share-body').innerHTML='<div class="cshare"><b>Loading video share…</b></div>';if(!dialog.open)dialog.showModal();try{await reload(false)}catch(err){document.getElementById('creator-share-body').innerHTML='<div class="cshare"><h2>Share with creator</h2><p>'+esc(err.message)+'</p><button data-cshare="close">Close</button></div>'}}
async function publish(){const {c,v}=ctx(),w=wid(),payload=snapshot();msg('Publishing…');info=await api({action:'publish',workspaceId:w,creatorId:String(c.id),videoId:String(v.id),payload});render();msg('Private video link is ready.')}
async function copy(){if(!info?.link?.token)return;const u=linkUrl(info.link.token);try{await navigator.clipboard.writeText(u);msg('Share link copied.')}catch{prompt('Copy this private video link:',u)}}
function openLink(){if(info?.link?.token)window.open(linkUrl(info.link.token),'_blank','noopener,noreferrer')}
async function rotate(){if(!confirm('Replace this private video link? The old link will stop working immediately.'))return;const {c,v}=ctx(),w=wid();await api({action:'rotate',workspaceId:w,creatorId:String(c.id),videoId:String(v.id),payload:snapshot()});await reload(false);msg('Link rotated. Copy the new link.')}
async function revoke(){if(!info?.link?.id||!confirm('Revoke this video link? The creator will no longer be able to open it.'))return;const {c,v}=ctx(),w=wid();await api({action:'revoke',workspaceId:w,creatorId:String(c.id),linkId:info.link.id});info={link:null,document:null};render();msg('Link revoked.');markButtons(v.id,false)}
function ensure(o,k){if(!o[k]||typeof o[k]!=='object'||Array.isArray(o[k]))o[k]={};return o[k]}
async function applyChanges(){const {c,v}=ctx(),w=wid();await reload(false);const shared=existing();if(!shared)return;const cr=shared.creator||{},pkg=ensure(v,'package'),hook=ensure(v,'hook'),pr=ensure(v,'promise'),st=ensure(v,'structure');let n=0;const put=(o,k,val)=>{if(typeof val==='string'&&val.trim()&&o[k]!==val){o[k]=val;n++}};put(pkg,'workingTitle',cr.titleDraft);put(pkg,'thumbnailText',cr.thumbnailTextDraft);put(pkg,'thumbnailConcept',cr.thumbnailConceptDraft);put(hook,'draft',cr.hookDraft);put(pr,'viewer',cr.viewerDraft);put(pr,'result',cr.promiseResultDraft);put(st,'notes',cr.outlineNotesDraft);const save=bind('save');if(typeof save==='function')save();const rer=bind('render');if(typeof rer==='function')rer();if(info?.link?.id)await api({action:'ack',workspaceId:w,creatorId:String(c.id),linkId:info.link.id});await reload(false);msg(n?('Applied '+n+' creator edit'+(n===1?'':'s')+' to this video.'):'Reviewed. No editable fields needed to change.');markButtons(v.id,false)}
function markButtons(videoId,review){document.querySelectorAll('[data-creator-share-video="'+CSS.escape(String(videoId))+'"]').forEach(b=>{b.dataset.review=review?'true':'false';if(b.classList.contains('creator-share-planner'))b.textContent=review?'Creator updates ready':'Share with creator';else b.textContent=review?'Review':'Share'})}
function makeButton(videoId,creatorId,planner=false){const b=document.createElement('button');b.type='button';b.dataset.creatorShareVideo=String(videoId);b.dataset.creatorShareCreator=String(creatorId);b.className=planner?'btn creator-share-planner':'tinybtn creator-share-inline';b.textContent=planner?'Share with creator':'Share';return b}
function inject(){
 css();const cc=currentCreator();
 document.querySelectorAll('.slot-row').forEach(row=>{const open=row.querySelector('button[data-action="open-video"]');if(!open||row.querySelector('[data-creator-share-video]')||!cc)return;const wrap=document.createElement('div');wrap.className='creator-share-row-actions';open.replaceWith(wrap);wrap.append(open,makeButton(open.dataset.id,cc.id,false))});
 document.querySelectorAll('.flow-top-row').forEach(top=>{const heading=top.querySelector('.video-heading'),actions=top.querySelector('.actions');if(!heading||!actions||actions.querySelector('.creator-share-planner')||!cc||!currentVideo())return;actions.insertBefore(makeButton(currentVideo().id,cc.id,true),actions.firstChild)});
}
document.addEventListener('click',e=>{const b=e.target.closest('[data-creator-share-video]');if(!b)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();openShare(b.dataset.creatorShareCreator,b.dataset.creatorShareVideo)},true);
new MutationObserver(()=>requestAnimationFrame(inject)).observe(document.documentElement,{childList:true,subtree:true});setTimeout(inject,900);
window.AcceleratorCreatorSharing={openVideo:openShare};
})();