(()=>{
if(window.__acceleratorCreatorSharing)return;window.__acceleratorCreatorSharing=true;
const ENDPOINT='https://pqggobwpazihraeqvspc.supabase.co/functions/v1/creator-portal',PUB='sb_publishable_VgGebMpW9tBcCiQlRdnzpA__rbATAaT',AUTH='sb-pqggobwpazihraeqvspc-auth-token';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function bind(n){try{return(0,eval)('typeof '+n+'!=="undefined"?'+n+':undefined')}catch{return undefined}}
function appState(){const s=bind('state');return s&&typeof s==='object'?s:null}
function getCreator(id){return appState()?.creators?.find(c=>String(c.id)===String(id))||null}
function getVideo(c,id){return c?.videos?.find(v=>String(v.id)===String(id))||null}
function currentCreator(){const s=appState();return getCreator(s?.currentCreatorId)}
function currentVideo(){const s=appState(),c=currentCreator();return getVideo(c,s?.currentVideoId)}
function wid(){try{return window.__acceleratorSaveDiagnostics?.().workspaceId||null}catch{return null}}
function tokenIn(x,d=0){if(!x||d>5)return null;if(typeof x==='object'){if(typeof x.access_token==='string')return x.access_token;for(const v of Object.values(x)){const t=tokenIn(v,d+1);if(t)return t}}return null}
function auth(){try{return tokenIn(JSON.parse(localStorage.getItem(AUTH)||'null'))}catch{return null}}
async function api(body){const t=auth();if(!t)throw new Error('Cloud sign-in is required before creating a share link.');const r=await fetch(ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json','apikey':PUB,'Authorization':'Bearer '+t},body:JSON.stringify(body),cache:'no-store'});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||('Request failed '+r.status));return d}
const obj=v=>v&&typeof v==='object'&&!Array.isArray(v)?v:{},str=v=>typeof v==='string'?v:'';
function source(v){const p=obj(v.package),pr=obj(v.promise),h=obj(v.hook),s=obj(v.structure);return{title:str(p.finalTitle)||str(p.workingTitle)||str(v.title),thumbnailText:str(p.thumbnailText),thumbnailConcept:str(p.thumbnailConcept),hookDraft:str(h.draft)||str(s.hook),viewer:str(pr.viewer)||str(v.viewer?.problem)||str(v.exactViewer),promiseResult:str(pr.result)||str(v.desiredOutcome),outlineNotes:str(s.notes),stage:str(v.stage),publishDate:str(v.publishDate)}}
function taskId(t){let h=2166136261;for(let i=0;i<t.length;i++){h^=t.charCodeAt(i);h=Math.imul(h,16777619)}return'task-'+(h>>>0).toString(36)}
const linkUrl=t=>location.origin+'/creator.html#'+encodeURIComponent(t);
let dialog=null,info=null,active=null,statusCreatorId='',statusLoading=false;
const statuses=new Map();

function css(){if(document.getElementById('creator-share-style'))return;const s=document.createElement('style');s.id='creator-share-style';s.textContent=`
.creator-share-row-actions{display:flex!important;gap:5px;align-items:center;justify-content:flex-end}
.slot-row:has(.creator-share-row-actions){grid-template-columns:44px 120px minmax(0,1fr) 170px 150px!important}
.creator-share-inline{white-space:nowrap;min-width:58px}
.creator-share-inline[data-review="true"],.creator-share-planner[data-review="true"]{border-color:#75ae96!important;background:#eef8f3!important;color:#23664d!important}
#creator-share-dialog{width:min(700px,94vw);max-height:92vh;border:1px solid #cbd6da;border-radius:15px;padding:0;background:var(--panel,#fff);color:var(--text,#17212b)}
.cshare{padding:20px}.cshare h2{margin:0 0 4px}.cshare .muted{opacity:.66}.cshare-head{display:flex;justify-content:space-between;gap:14px}
.cshare-actions{display:flex;gap:8px;flex-wrap:wrap;margin:14px 0}.cshare button,.cshare-open-link{border:1px solid var(--line,#d8e0e3);background:var(--panel,#fff);color:inherit;border-radius:9px;padding:9px 12px;font-weight:800;cursor:pointer;text-decoration:none;display:inline-flex;align-items:center;justify-content:center}.cshare-open-link{min-width:0;padding-inline:12px}
.cshare button.primary{background:#234f52;color:#fff;border-color:#234f52}.cshare button.danger{color:#9a3d3d}
.cshare textarea{width:100%;min-height:94px;border:1px solid var(--line,#d8e0e3);border-radius:9px;padding:9px;background:transparent;color:inherit;font:inherit;resize:vertical}
.cshare label{display:grid;gap:5px;font-size:12px;font-weight:800;margin-top:13px}.cshare-review{padding:11px;border-radius:10px;background:rgba(47,132,100,.09);margin:12px 0}
.cshare-note{padding:9px;border-left:3px solid #55757a;background:rgba(85,117,122,.06);margin-top:8px;font-size:13px}.cshare-link{font-size:11px;overflow-wrap:anywhere}.cshare-msg{min-height:20px;font-size:12px;margin-top:8px}
@media(max-width:1200px){.slot-row:has(.creator-share-row-actions){grid-template-columns:42px 110px minmax(0,1fr) 150px!important}.slot-row:has(.creator-share-row-actions)>.slot-role{display:none!important}.slot-row:has(.creator-share-row-actions)>.creator-share-row-actions{display:flex!important}}
@media(max-width:760px){.cshare-head{display:block}.slot-row:has(.creator-share-row-actions){grid-template-columns:36px minmax(0,1fr)!important}.slot-row:has(.creator-share-row-actions)>*:nth-child(2),.slot-row:has(.creator-share-row-actions)>.slot-role{display:none!important}.slot-row:has(.creator-share-row-actions)>.creator-share-row-actions{grid-column:1/-1;justify-self:end;display:flex!important;margin-top:3px}.creator-share-inline{padding-inline:8px!important}}
`;document.head.appendChild(s)}
function ensureDialog(){if(dialog)return dialog;css();dialog=document.createElement('dialog');dialog.id='creator-share-dialog';dialog.innerHTML='<div id="creator-share-body"></div>';document.body.appendChild(dialog);dialog.addEventListener('click',async e=>{const a=e.target.closest('[data-cshare]')?.dataset.cshare;if(!a)return;try{if(a==='close')dialog.close();else if(a==='publish')await publish();else if(a==='copy')await copy();else if(a==='refresh')await reload(true);else if(a==='apply')await applyChanges();else if(a==='rotate')await rotate();else if(a==='revoke')await revoke()}catch(err){msg(err.message||'Something went wrong.',true)}});return dialog}
function ctx(){const c=getCreator(active?.creatorId),v=getVideo(c,active?.videoId);return{c,v}}
function existing(){return info?.document?.payload?.videos?.[0]||null}
function taskProgress(ex){const tasks=ex?.coach?.tasks||[],done=new Set(ex?.creator?.completedTaskIds||[]);return tasks.length?done.size+'/'+tasks.length+' tasks complete':''}
function render(){const {c,v}=ctx();if(!c||!v)return;const ex=existing(),cr=ex?.creator||{},link=info?.link,review=!!info?.document?.needsReview,title=source(v).title||'Untitled video',tasks=(ex?.coach?.tasks||[]).map(t=>t.text).join('\n'),progress=taskProgress(ex),status=cr.status||'';
document.getElementById('creator-share-body').innerHTML='<div class="cshare"><div class="cshare-head"><div><div class="muted">Share this video</div><h2>'+esc(title)+'</h2><div class="muted">'+esc(c.name)+' · no creator account required</div></div><button data-cshare="close">Close</button></div>'+
(review?'<div class="cshare-review"><b>Creator changes are ready for review.</b>'+((status||progress)?'<div class="muted" style="margin-top:4px">'+esc([status,progress].filter(Boolean).join(' · '))+'</div>':'')+(cr.notes?'<div class="cshare-note">'+esc(cr.notes)+'</div>':'')+'</div>':'')+
'<label>What should they work on?<textarea id="cshare-direction">'+esc(ex?.coach?.direction||'')+'</textarea></label>'+
'<label>Next steps, one per line<textarea id="cshare-tasks">'+esc(tasks)+'</textarea></label>'+
'<div class="muted" style="margin-top:12px">They can work on the title, thumbnail, hook, viewer, promise, outline, notes, and task status. Your internal strategy and analytics are never shared.</div>'+
'<div class="cshare-actions"><button class="primary" data-cshare="publish">'+(link?'Update shared video':'Create & copy private link')+'</button>'+(link?'<button data-cshare="copy">Copy link</button><a class="cshare-open-link" href="'+esc(linkUrl(link.token))+'" target="_blank" rel="noopener noreferrer" title="Open the creator view in a new tab">Preview</a><button data-cshare="refresh">Check updates</button>':'')+(review?'<button class="primary" data-cshare="apply">Apply creator changes</button>':'')+'</div>'+
(link?'<div class="cshare-link muted">'+esc(linkUrl(link.token))+'</div><div class="cshare-actions"><button data-cshare="rotate">Rotate link</button><button class="danger" data-cshare="revoke">Revoke link</button></div>':'')+'<div id="cshare-msg" class="cshare-msg"></div></div>';
updateButton(active.videoId,link?true:false,review)}
function msg(t,bad=false){const e=document.getElementById('cshare-msg');if(e){e.textContent=t;e.style.color=bad?'#a33':'inherit'}}
function snapshot(){const {c,v}=ctx(),s=source(v),lines=(document.getElementById('cshare-tasks')?.value||'').split(/\n+/).map(x=>x.trim()).filter(Boolean).slice(0,20);return{schemaVersion:1,creator:{id:String(c.id),name:c.name||'',channelName:c.channelName||'',instructions:''},videos:[{id:String(v.id),coach:{...s,direction:document.getElementById('cshare-direction')?.value||'',tasks:lines.map(t=>({id:taskId(t),text:t}))},creator:{}}]}}
async function reload(show=false){const {c,v}=ctx(),w=wid();if(!c||!v)return;if(!w)throw new Error('Cloud workspace is still loading. Try again in a moment.');info=await api({action:'owner-get',workspaceId:w,creatorId:String(c.id),videoId:String(v.id)});render();if(show)msg('Checked for creator updates.')}
async function openShare(creatorId,videoId){active={creatorId:String(creatorId),videoId:String(videoId)};const {c,v}=ctx();if(!c||!v)return;ensureDialog();document.getElementById('creator-share-body').innerHTML='<div class="cshare"><b>Loading video share…</b></div>';if(!dialog.open)dialog.showModal();try{await reload(false)}catch(err){document.getElementById('creator-share-body').innerHTML='<div class="cshare"><h2>Share with creator</h2><p>'+esc(err.message)+'</p><button data-cshare="close">Close</button></div>'}}
async function publish(){const {c,v}=ctx(),w=wid(),payload=snapshot(),isNew=!info?.link;msg(isNew?'Creating link…':'Updating…');info=await api({action:'publish',workspaceId:w,creatorId:String(c.id),videoId:String(v.id),payload});render();await refreshStatuses(true);if(isNew){try{await navigator.clipboard.writeText(linkUrl(info.link.token));msg('Private link created and copied.')}catch{msg('Private link created. Use Copy link to copy it.')}}else msg('Shared video updated.')}
async function copy(){if(!info?.link?.token)return;const u=linkUrl(info.link.token);try{await navigator.clipboard.writeText(u);msg('Share link copied.')}catch{prompt('Copy this private video link:',u)}}
async function rotate(){if(!confirm('Replace this private video link? The old link will stop working immediately.'))return;const {c,v}=ctx(),w=wid();await api({action:'rotate',workspaceId:w,creatorId:String(c.id),videoId:String(v.id),payload:snapshot()});await reload(false);await refreshStatuses(true);msg('Link rotated. Copy the new link.')}
async function revoke(){if(!info?.link?.id||!confirm('Revoke this video link? The creator will no longer be able to open it.'))return;const {c,v}=ctx(),w=wid();await api({action:'revoke',workspaceId:w,creatorId:String(c.id),linkId:info.link.id});info={link:null,document:null};statuses.delete(String(v.id));render();applyStatuses();msg('Link revoked.')}
function ensure(o,k){if(!o[k]||typeof o[k]!=='object'||Array.isArray(o[k]))o[k]={};return o[k]}
async function applyChanges(){const {c,v}=ctx(),w=wid();await reload(false);const shared=existing();if(!shared)return;const cr=shared.creator||{},pkg=ensure(v,'package'),hook=ensure(v,'hook'),pr=ensure(v,'promise'),st=ensure(v,'structure');let n=0;const put=(o,k,val)=>{if(typeof val==='string'&&val.trim()&&o[k]!==val){o[k]=val;n++}};put(pkg,'workingTitle',cr.titleDraft);put(pkg,'thumbnailText',cr.thumbnailTextDraft);put(pkg,'thumbnailConcept',cr.thumbnailConceptDraft);put(hook,'draft',cr.hookDraft);put(pr,'viewer',cr.viewerDraft);put(pr,'result',cr.promiseResultDraft);put(st,'notes',cr.outlineNotesDraft);const save=bind('save');if(typeof save==='function')save();const rer=bind('render');if(typeof rer==='function')rer();if(info?.link?.id)await api({action:'ack',workspaceId:w,creatorId:String(c.id),linkId:info.link.id});await reload(false);await refreshStatuses(true);msg(n?('Applied '+n+' creator edit'+(n===1?'':'s')+' to this video.'):'Reviewed. No editable fields needed to change.')}
function updateButton(videoId,shared,review){document.querySelectorAll('[data-creator-share-video="'+CSS.escape(String(videoId))+'"]').forEach(b=>{b.dataset.review=review?'true':'false';b.dataset.shared=shared?'true':'false';if(b.classList.contains('creator-share-planner'))b.textContent=review?'Creator updates ready':shared?'Shared with creator':'Share with creator';else b.textContent=review?'Review':shared?'Shared':'Share'})}
function applyStatuses(){document.querySelectorAll('[data-creator-share-video]').forEach(b=>{const s=statuses.get(String(b.dataset.creatorShareVideo));updateButton(b.dataset.creatorShareVideo,!!s,!!s?.needsReview)})}
function makeButton(videoId,creatorId,planner=false){const b=document.createElement('button');b.type='button';b.dataset.creatorShareVideo=String(videoId);b.dataset.creatorShareCreator=String(creatorId);b.className=planner?'btn creator-share-planner':'tinybtn creator-share-inline';const s=statuses.get(String(videoId));b.textContent=planner?(s?.needsReview?'Creator updates ready':s?'Shared with creator':'Share with creator'):(s?.needsReview?'Review':s?'Shared':'Share');if(s?.needsReview)b.dataset.review='true';if(s)b.dataset.shared='true';return b}
async function refreshStatuses(force=false){const c=currentCreator(),w=wid();if(!c||!w||statusLoading)return;if(!force&&statusCreatorId===String(c.id)&&statuses.size)return;statusLoading=true;try{const data=await api({action:'owner-list',workspaceId:w,creatorId:String(c.id)});if(String(c.id)!==String(currentCreator()?.id))return;statuses.clear();for(const item of data.links||[])statuses.set(String(item.videoId),item);statusCreatorId=String(c.id);applyStatuses()}catch{}finally{statusLoading=false}}
function inject(){css();const cc=currentCreator();document.querySelectorAll('.slot-row').forEach(row=>{const open=row.querySelector('button[data-action="open-video"]');if(!open||row.querySelector('[data-creator-share-video]')||!cc)return;const wrap=document.createElement('div');wrap.className='creator-share-row-actions';open.replaceWith(wrap);wrap.append(open,makeButton(open.dataset.id,cc.id,false))});document.querySelectorAll('.flow-top-row').forEach(top=>{const heading=top.querySelector('.video-heading'),actions=top.querySelector('.actions');if(!heading||!actions||actions.querySelector('.creator-share-planner')||!cc||!currentVideo())return;actions.insertBefore(makeButton(currentVideo().id,cc.id,true),actions.firstChild)});applyStatuses()}
document.addEventListener('click',e=>{const b=e.target.closest('[data-creator-share-video]');if(!b)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();openShare(b.dataset.creatorShareCreator,b.dataset.creatorShareVideo)},true);
let lastCreator='';function observe(){inject();const id=String(currentCreator()?.id||'');if(id!==lastCreator){lastCreator=id;statuses.clear();statusCreatorId='';if(id)setTimeout(()=>refreshStatuses(true),250)}}
new MutationObserver(()=>requestAnimationFrame(observe)).observe(document.documentElement,{childList:true,subtree:true});setInterval(()=>{if(document.visibilityState==='visible')refreshStatuses(true)},60000);setTimeout(observe,700);
window.AcceleratorCreatorSharing={openVideo:openShare,refresh:()=>refreshStatuses(true)};
})();