create table if not exists public.creator_portal_links (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  creator_id text not null,
  creator_name text not null default '',
  scope text not null default 'creator' check (scope in ('creator','video')),
  video_id text null,
  token_hash text not null unique,
  token_secret text not null,
  created_by uuid not null references auth.users(id) on delete cascade,
  expires_at timestamptz null,
  revoked_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists creator_portal_one_active_creator_link
  on public.creator_portal_links(workspace_id, creator_id)
  where revoked_at is null and scope='creator' and video_id is null;
create index if not exists creator_portal_links_workspace_creator_idx
  on public.creator_portal_links(workspace_id, creator_id, created_at desc);
alter table public.creator_portal_links enable row level security;
create table if not exists public.creator_portal_documents (
  link_id uuid primary key references public.creator_portal_links(id) on delete cascade,
  payload jsonb not null default '{}'::jsonb,
  version bigint not null default 1 check (version > 0),
  last_actor text not null default 'coach' check (last_actor in ('coach','creator')),
  coach_updated_at timestamptz null,
  creator_updated_at timestamptz null,
  updated_at timestamptz not null default now()
);
alter table public.creator_portal_documents enable row level security;
create table if not exists public.creator_portal_activity (
  id bigint generated by default as identity primary key,
  link_id uuid not null references public.creator_portal_links(id) on delete cascade,
  actor text not null check (actor in ('coach','creator','system')),
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists creator_portal_activity_link_created_idx on public.creator_portal_activity(link_id, created_at desc);
alter table public.creator_portal_activity enable row level security;
comment on table public.creator_portal_links is 'Capability links for no-sign-in creator collaboration. Direct table access is intentionally blocked by RLS; use the creator-portal Edge Function.';
comment on table public.creator_portal_documents is 'Creator-safe collaboration payload only. Never store the full Accelerator workspace state here.';
